const fs = require('fs');

const missing_keys_en = {
  "forgot_pass": "Forgot password?",
  "dont_have_acc": "Don't have an account?",
  "create_account": "Create account",
  "login_title": "Login",
  "login_subtitle": "Sign in to your account",
  "email_label": "Email Address",
  "email_placeholder": "Enter your email",
  "password_label": "Password",
  "password_placeholder": "Enter your password",
  "login_btn": "Login",
  "login_error_invalid": "Invalid email or password",
  "login_error_unverified": "Please verify your email",
  "login_error_general": "Login failed. Try again.",
  "register_title": "Create New Account",
  "register_subtitle": "Join PORABOO",
  "already_have_acc": "Already have an account?",
  "login_here": "Login",
  "register_btn": "Register",
  "select_role": "Who are you?",
  "role_tutor": "I am a Tutor",
  "role_guardian": "I am a Guardian",
  "full_name_label": "Full Name",
  "full_name_placeholder": "Your full name",
  "phone_label": "Phone Number",
  "phone_placeholder": "01XXXXXXXXX",
  "email_verify_sent": "Verification email sent!",
  "email_verify_check": "Please check your email",
  "forgot_title": "Reset Password",
  "forgot_subtitle": "We'll send a reset link to your email",
  "forgot_btn": "Send Reset Link",
  "forgot_back": "Back to Login",
  "forgot_success": "Reset link sent!",
  "nav_home": "Home",
  "nav_feed": "Feed",
  "nav_jobs": "Job Board",
  "nav_login": "Login",
  "nav_start": "Get Started",
  "nav_profile": "My Profile",
  "nav_settings": "Settings",
  "nav_logout": "Logout",
  "feed_placeholder": "What's on your mind? Share...",
  "feed_post_btn": "Post",
  "feed_visibility_public": "Public",
  "feed_visibility_tutors": "Tutors Only",
  "feed_visibility_guardians": "Guardians Only",
  "feed_warning": "⚠️ Do not share phone/email",
  "feed_add_image": "Add Photo",
  "feed_like": "Like",
  "feed_comment": "Comment",
  "feed_share": "Share",
  "feed_connect": "Connect",
  "feed_connected": "Connected ✓",
  "feed_pending": "Request Sent",
  "feed_no_posts": "No posts yet",
  "feed_loading": "Loading posts...",
  "feed_recent_jobs": "Recent Jobs",
  "feed_see_more": "See More",
  "feed_suggestions": "People you may know",
  "job_board_title": "Job Board",
  "job_board_subtitle": "Find tuition jobs and apply",
  "job_new_post": "Post New Job",
  "job_my_applications": "My Applications",
  "job_apply": "Apply Now",
  "job_applied": "Applied ✓",
  "job_view_applicants": "View Applicants",
  "job_filter_subject": "Subject",
  "job_filter_area": "Area",
  "job_filter_class": "Class",
  "job_filter_budget": "Budget",
  "job_filter_reset": "Reset",
  "job_no_posts": "No job posts found",
  "job_per_month": "/month",
  "job_days_week": "days/week",
  "job_days": "days",
  "job_ago": "ago",
  "job_male_pref": "Male tutor preferred",
  "job_female_pref": "Female tutor preferred",
  "job_no_pref": "No preference",
  "profile_edit": "Edit Profile",
  "profile_add_bio": "+ Add Bio",
  "profile_posts_tab": "Posts",
  "profile_about_tab": "About",
  "profile_connections_tab": "Connections",
  "profile_photos_tab": "Photos",
  "profile_no_posts": "No posts yet",
  "profile_connections": "Connections",
  "profile_hire": "Hire Tutor",
  "profile_intro": "Intro",
  "profile_education": "Education",
  "profile_experience": "Experience",
  "profile_subjects": "Subjects",
  "profile_area": "Location",
  "profile_others": "Others",
  "profile_edit_info": "Edit Details",
  "profile_save": "Save",
  "profile_cancel": "Cancel",
  "profile_change_cover": "Change Cover Photo",
  "profile_joined": "Joined",
  "profile_last_active": "Last active",
  "settings_title": "Settings",
  "settings_account": "Account",
  "settings_security": "Security",
  "settings_notifications": "Notifications",
  "settings_privacy": "Privacy",
  "settings_language": "Language",
  "settings_save": "Save Changes",
  "settings_change_pass": "Change Password",
  "settings_current_pass": "Current Password",
  "settings_new_pass": "New Password",
  "settings_confirm_pass": "Confirm Password",
  "settings_delete_acc": "Delete Account",
  "onboard_title": "Complete Your Profile",
  "onboard_subtitle": "Fill in your details to start",
  "onboard_save": "Save Profile",
  "onboard_next": "Next",
  "onboard_back": "Back",
  "onboard_required": "Required",
  "onboard_optional": "Optional",
  "onboard_progress": "Profile Completion",
  "loading": "Loading...",
  "save": "Save",
  "cancel": "Cancel",
  "edit": "Edit",
  "delete": "Delete",
  "confirm": "Confirm",
  "success": "Success!",
  "error": "Something went wrong. Try again.",
  "required": "Required",
  "optional": "Optional",
  "search": "Search",
  "filter": "Filter",
  "submit": "Submit",
  "back": "Back",
  "next": "Next",
  "yes": "Yes",
  "no": "No",
  "close": "Close",
  "copied": "Copied ✓"
};

const missing_keys_bn = {
  "forgot_pass": "পাসওয়ার্ড ভুলে গেছেন?",
  "dont_have_acc": "অ্যাকাউন্ট নেই?",
  "create_account": "অ্যাকাউন্ট তৈরি করুন",
  "login_title": "লগইন করুন",
  "login_subtitle": "আপনার অ্যাকাউন্টে প্রবেশ করুন",
  "email_label": "ইমেইল ঠিকানা",
  "email_placeholder": "আপনার ইমেইল লিখুন",
  "password_label": "পাসওয়ার্ড",
  "password_placeholder": "আপনার পাসওয়ার্ড লিখুন",
  "login_btn": "লগইন করুন",
  "login_error_invalid": "ইমেইল বা পাসওয়ার্ড সঠিক নয়",
  "login_error_unverified": "আপনার ইমেইল যাচাই করুন",
  "login_error_general": "লগইন ব্যর্থ হয়েছে",
  "register_title": "নতুন অ্যাকাউন্ট তৈরি করুন",
  "register_subtitle": "PORABOO-তে যোগ দিন",
  "already_have_acc": "ইতিমধ্যে অ্যাকাউন্ট আছে?",
  "login_here": "লগইন করুন",
  "register_btn": "নিবন্ধন করুন",
  "select_role": "আপনি কে?",
  "role_tutor": "আমি একজন টিউটর",
  "role_guardian": "আমি একজন Guardian",
  "full_name_label": "পুরো নাম",
  "full_name_placeholder": "আপনার পুরো নাম",
  "phone_label": "ফোন নম্বর",
  "phone_placeholder": "01XXXXXXXXX",
  "email_verify_sent": "যাচাই ইমেইল পাঠানো হয়েছে!",
  "email_verify_check": "আপনার ইমেইল চেক করুন",
  "forgot_title": "পাসওয়ার্ড রিসেট করুন",
  "forgot_subtitle": "আপনার ইমেইলে রিসেট লিংক পাঠানো হবে",
  "forgot_btn": "রিসেট লিংক পাঠান",
  "forgot_back": "লগইনে ফিরে যান",
  "forgot_success": "রিসেট লিংক পাঠানো হয়েছে!",
  "nav_home": "মূল পাতা",
  "nav_feed": "ফিড",
  "nav_jobs": "জব বোর্ড",
  "nav_login": "লগইন",
  "nav_start": "শুরু করুন",
  "nav_profile": "আমার প্রোফাইল",
  "nav_settings": "সেটিংস",
  "nav_logout": "লগআউট",
  "feed_placeholder": "কী মনে আছে? শেয়ার করুন...",
  "feed_post_btn": "পোস্ট করুন",
  "feed_visibility_public": "সবাই",
  "feed_visibility_tutors": "শুধু টিউটর",
  "feed_visibility_guardians": "শুধু Guardian",
  "feed_warning": "⚠️ ফোন/ইমেইল শেয়ার করবেন না",
  "feed_add_image": "ছবি যোগ করুন",
  "feed_like": "লাইক",
  "feed_comment": "মন্তব্য",
  "feed_share": "শেয়ার",
  "feed_connect": "সংযুক্ত হন",
  "feed_connected": "সংযুক্ত ✓",
  "feed_pending": "অনুরোধ পাঠানো হয়েছে",
  "feed_no_posts": "এখনো কোনো পোস্ট নেই",
  "feed_loading": "পোস্ট লোড হচ্ছে...",
  "feed_recent_jobs": "সাম্প্রতিক জব",
  "feed_see_more": "আরও দেখুন",
  "feed_suggestions": "পরিচিত টিউটর",
  "job_board_title": "জব বোর্ড",
  "job_board_subtitle": "টিউশন জব খুঁজুন এবং আবেদন করুন",
  "job_new_post": "নতুন পোস্ট করুন",
  "job_my_applications": "আমার আবেদনসমূহ",
  "job_apply": "আবেদন করুন",
  "job_applied": "আবেদন করা হয়েছে ✓",
  "job_view_applicants": "আবেদনকারী দেখুন",
  "job_filter_subject": "বিষয়",
  "job_filter_area": "এলাকা",
  "job_filter_class": "ক্লাস",
  "job_filter_budget": "বাজেট",
  "job_filter_reset": "রিসেট",
  "job_no_posts": "কোনো জব পোস্ট নেই",
  "job_per_month": "/মাস",
  "job_days_week": "সপ্তাহে",
  "job_days": "দিন",
  "job_ago": "আগে",
  "job_male_pref": "পুরুষ টিউটর পছন্দ",
  "job_female_pref": "মহিলা টিউটর পছন্দ",
  "job_no_pref": "যেকোনো",
  "profile_edit": "প্রোফাইল সম্পাদনা করুন",
  "profile_add_bio": "+ বায়ো যোগ করুন",
  "profile_posts_tab": "পোস্টসমূহ",
  "profile_about_tab": "তথ্য",
  "profile_connections_tab": "সংযোগ",
  "profile_photos_tab": "ছবি",
  "profile_no_posts": "এখনো কোনো পোস্ট নেই",
  "profile_connections": "সংযোগ",
  "profile_hire": "নিয়োগ করুন",
  "profile_intro": "পরিচিতি",
  "profile_education": "শিক্ষাগত যোগ্যতা",
  "profile_experience": "অভিজ্ঞতা",
  "profile_subjects": "বিষয়সমূহ",
  "profile_area": "এলাকা",
  "profile_others": "অন্যান্য",
  "profile_edit_info": "তথ্য সম্পাদনা করুন",
  "profile_save": "সংরক্ষণ করুন",
  "profile_cancel": "বাতিল",
  "profile_change_cover": "কভার ফটো পরিবর্তন করুন",
  "profile_joined": "যোগ দিয়েছেন",
  "profile_last_active": "সর্বশেষ সক্রিয়",
  "settings_title": "সেটিংস",
  "settings_account": "অ্যাকাউন্ট",
  "settings_security": "নিরাপত্তা",
  "settings_notifications": "নোটিফিকেশন",
  "settings_privacy": "গোপনীয়তা",
  "settings_language": "ভাষা",
  "settings_save": "সংরক্ষণ করুন",
  "settings_change_pass": "পাসওয়ার্ড পরিবর্তন করুন",
  "settings_current_pass": "বর্তমান পাসওয়ার্ড",
  "settings_new_pass": "নতুন পাসওয়ার্ড",
  "settings_confirm_pass": "পাসওয়ার্ড নিশ্চিত করুন",
  "settings_delete_acc": "অ্যাকাউন্ট মুছে ফেলুন",
  "onboard_title": "প্রোফাইল সম্পন্ন করুন",
  "onboard_subtitle": "টিউশন খোঁজা শুরু করতে প্রোফাইল পূরণ করুন",
  "onboard_save": "সংরক্ষণ করুন",
  "onboard_next": "পরবর্তী",
  "onboard_back": "পূর্ববর্তী",
  "onboard_required": "আবশ্যক",
  "onboard_optional": "ঐচ্ছিক",
  "onboard_progress": "প্রোফাইল সম্পূর্ণতা",
  "loading": "লোড হচ্ছে...",
  "save": "সংরক্ষণ করুন",
  "cancel": "বাতিল",
  "edit": "সম্পাদনা করুন",
  "delete": "মুছুন",
  "confirm": "নিশ্চিত করুন",
  "success": "সফল হয়েছে!",
  "error": "কিছু ভুল হয়েছে। আবার চেষ্টা করুন।",
  "required": "আবশ্যক",
  "optional": "ঐচ্ছিক",
  "search": "খুঁজুন",
  "filter": "ফিল্টার",
  "submit": "জমা দিন",
  "back": "পিছনে",
  "next": "পরবর্তী",
  "yes": "হ্যাঁ",
  "no": "না",
  "close": "বন্ধ করুন",
  "copied": "কপি হয়েছে ✓"
};

let content = fs.readFileSync('src/lib/translations.ts', 'utf8');

function inject(lang, keys) {
  const langHeader = `  ${lang}: {`;
  const startIdx = content.indexOf(langHeader);
  if (startIdx === -1) return;
  
  const insertPos = startIdx + langHeader.length;
  
  let injectStr = "\n";
  for (const [k, v] of Object.entries(keys)) {
    // Escape quotes in values
    const safeV = v.replace(/"/g, '\\"');
    injectStr += `    "${k}": "${safeV}",\n`;
  }
  
  content = content.slice(0, insertPos) + injectStr + content.slice(insertPos);
}

inject('en', missing_keys_en);
inject('bn', missing_keys_bn);

fs.writeFileSync('src/lib/translations.ts', content);
